# Generated by Django 3.2.18 on 2023-06-07 12:08

import core.models.inouts.pair
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230607_0811'),
        ('bots', '0002_auto_20230126_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='ordermatch',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='ordermatchstat',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
    ]
