# Generated by Django 3.2.18 on 2023-03-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230302_0950'),
        ('cryptocoins', '0002_auto_20230117_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accumulationstate',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='BNBWithdrawalApprove',
        ),
        migrations.DeleteModel(
            name='TRXWithdrawalApprove',
        ),
        migrations.RemoveField(
            model_name='accumulationtransaction',
            name='accumulation_state',
        ),
        migrations.AddField(
            model_name='accumulationtransaction',
            name='wallet_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.wallettransactions'),
        ),
        migrations.DeleteModel(
            name='AccumulationState',
        ),
    ]
