PENDING = 0
EXECUTED = 1
CANCELLED = 2

DISABLE_TOPUPS = 'disable_topups'
DISABLE_WITHDRAWALS = 'disable_withdrawals'
DISABLE_EXCHANGE = 'disable_exchange'
DISABLE_PAIRS = 'disable_pairs'
DISABLE_STACK = 'disable_stack'
DISABLE_ALL = 'disable_all'

DISABLE_COIN_STATES = [
    DISABLE_TOPUPS, DISABLE_WITHDRAWALS, DISABLE_EXCHANGE,
    DISABLE_PAIRS, DISABLE_STACK, DISABLE_ALL
]
