# Generated by Django 3.2.7 on 2023-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wallettransactions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesandlimits',
            name='limits_keeper_accumulation_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32),
        ),
    ]
