# Generated by Django 3.2.7 on 2023-02-10 13:28

from django.db import migrations
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wallettransactions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchangehistory',
            name='stop',
            field=lib.fields.MoneyField(blank=True, decimal_places=8, max_digits=32, null=True),
        ),
    ]
