# Generated by Django 3.2.18 on 2023-02-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feesandlimits_limits_keeper_accumulation_balance'),
        ('core', '0005_orderchangehistory_stop'),
    ]

    operations = [
    ]
