# Generated by Django 3.2.7 on 2023-02-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feesandlimits_limits_keeper_accumulation_balance'),
        ('core', '0005_orderchangehistory_stop'),
    ]

    operations = [
    ]
