# Generated by Django 3.2.18 on 2023-03-02 09:50

from django.db import migrations, models
import lib.fields


def mark_states(apps, schema_editor):
    WalletTransactions = apps.get_model('core', 'WalletTransactions')
    WalletTransactions.objects.all().update(state=12, monitoring_state=2)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20230220_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransactions',
            options={},
        ),
        migrations.AddField(
            model_name='userwallet',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='external_accumulation_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='fee_amount',
            field=lib.fields.MoneyField(decimal_places=8, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='monitoring_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not checked'), (2, 'Accumulated'), (3, 'Not accumulated'), (4, 'Wrong amount'), (5, 'Wrong accumulation')], default=1),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Verification failed'), (3, 'Waiting for KYT approve'), (4, 'KYT approve on check'), (5, 'KYT approve platform error'), (6, 'KYT approve rejected'), (7, 'Waiting for accumulation'), (8, 'Gas Required'), (9, 'Waiting for gas'), (10, 'Ready for accumulation'), (11, 'Accumulation in progress'), (12, 'Accumulated'), (13, 'Balance too low'), (14, 'Manual deposit'), (15, 'Old wallet deposit'), (16, 'External accumulated')], default=1),
        ),
        migrations.AddIndex(
            model_name='wallettransactions',
            index=models.Index(fields=['state'], name='core_wallet_state_129880_idx'),
        ),
        migrations.RunPython(mark_states),
    ]
