# Generated by Django 3.2.18 on 2023-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230315_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsettings',
            name='enable_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
