# Generated by Django 3.2.18 on 2023-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pairsettings_enable_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coininfo',
            name='logo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
