# Generated by Django 3.2.18 on 2023-06-07 08:11

import core.models.inouts.pair
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pair_data_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coininfo',
            name='tx_explorer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionresult',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='externalpriceshistory',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='pairsettings',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair', unique=True),
        ),
        migrations.AlterField(
            model_name='paygatetopup',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sourceoffunds',
            name='is_beneficiary',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tradesaggregatedstats',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='internal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='kyc_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpairdailystat',
            name='pair',
            field=core.models.inouts.pair.PairModelField(on_delete=django.db.models.deletion.CASCADE, to='core.pair'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
