# Generated by Django 3.2.18 on 2023-06-07 08:11

import core.models.inouts.pair
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230607_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='Pair',
            unique_together={('base', 'quote')},
        ),
    ]
