# Generated by Django 3.2.7 on 2023-01-17 16:17

import admin_panel.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_email_max_length'),
        ('core', '0004_alter_wallettransactions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.order'),
        ),
        migrations.CreateModel(
            name='AllOrderNoBot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.order'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.balance'),
        ),
        migrations.CreateModel(
            name='BlockedAddresses',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Blocked Addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userwallet',),
        ),
        migrations.CreateModel(
            name='EmailAddressVerified',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'account.emailaddress'),
        ),
        migrations.CreateModel(
            name='ExchangeFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.userfee'),
        ),
        migrations.CreateModel(
            name='ExchangeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.executionresult'),
        ),
        migrations.CreateModel(
            name='RefDetails',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Ref program details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', admin_panel.models.RefManager()),
            ],
        ),
        migrations.CreateModel(
            name='Topups',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.transaction'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.transaction'),
        ),
        migrations.CreateModel(
            name='UserDailyStat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.userpairdailystat'),
        ),
        migrations.CreateModel(
            name='UserKYCProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User KYC',
                'verbose_name_plural': 'Users KYC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userkyc',),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.transaction'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(admin_panel.models.MetaMixIn, 'core.withdrawalrequest'),
        ),
    ]
