from exchange.settings import env

IS_KYC_ENABLED = env('IS_KYC_ENABLED', default=False)
IS_KYC_REQUIRED = env('IS_KYC_REQUIRED', default=False)
SUMSUB_SECRET_KEY = env('SUMSUB_SECRET_KEY')
SUMSUB_APP_TOKEN = env('SUMSUB_APP_TOKEN')
SUMSUM_CALLBACK_VALIDATION_SECRET = env('SUMSUM_CALLBACK_VALIDATION_SECRET')


KYC_DATA_UPDATE_PERIOD = 7 * 24 * 60 * 60  # every week
KYC_DATA_UPDATE_TASKS_AT_ONCE = 50  # how many tasks plan
