# Generated by Django 3.2.7 on 2022-08-12 12:45

import admin_rest.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='AllOrderNoBot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.balance',),
        ),
        migrations.CreateModel(
            name='BalanceSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.balance',),
        ),
        migrations.CreateModel(
            name='ExchangeFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userfee',),
        ),
        migrations.CreateModel(
            name='ExchangeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.executionresult',),
        ),
        migrations.CreateModel(
            name='RefDetails',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Ref program details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', admin_rest.models.RefManager()),
            ],
        ),
        migrations.CreateModel(
            name='Topups',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='UserDailyStat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userpairdailystat',),
        ),
        migrations.CreateModel(
            name='UserKYCProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User KYC',
                'verbose_name_plural': 'Users KYC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userkyc',),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawalrequest',),
        ),
    ]
