# Generated by Django 3.2.7 on 2022-08-12 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(blank=True, default=None, max_length=250)),
                ('subject_ru', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('subject_en', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('text', models.TextField(blank=True, default=None)),
                ('text_ru', models.TextField(blank=True, default=None, null=True)),
                ('text_en', models.TextField(blank=True, default=None, null=True)),
                ('users', models.ManyToManyField(null=True, related_name='mailing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=255)),
                ('title_ru', models.CharField(default='', max_length=255, null=True)),
                ('title_en', models.CharField(default='', max_length=255, null=True)),
                ('text', models.TextField(default='')),
                ('text_ru', models.TextField(default='', null=True)),
                ('text_en', models.TextField(default='', null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Splash'), (2, 'Success message'), (3, 'Fail message')], default=1)),
                ('users', models.ManyToManyField(null=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailingProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='notifications.mailing')),
            ],
        ),
    ]
